sudo: false

language: haskell

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
before_script:
  - mysql -uroot -e 'create database yesodapi_test;'
  - mysql -uroot -e 'use yesodapi_test; show tables;'
  - mysql -uroot -e "use yesodapi_test; CREATE TABLE `comment` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `message` text NOT NULL,
    `user_id` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `comment_user_id_fkey` (`user_id`),
    CONSTRAINT `comment_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;"
before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
  - stack setup
after_install:
  - stack update
  - stack build
script:
  - stack test

services:
  - mysql
